# Custom Language File for Launcher Customizer

[ejs.app]
title = "Minefire"

[ejs.landing]
mediaGitHubURL = "https://github.com/Minefirefr"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/EcKTR9zWDW"

[ejs.settings]
sourceGithubLink = "https://github.com/Minefirefr"
supportLink = "https://github.com/Minefirefr/issues"

[ejs.welcome]
welcomeHeader = "Bienvenu sur Minefire"
welcomeDescription = "Bienvenue sur HunterZ, un serveur Minecraft où l’apocalypse a pris possession du monde !
            Dans ce paysage dévasté, les villes autrefois prospères sont désormais envahies par des hordes d’infectés, et chaque coin de rue est une nouvelle menace."
welcomeDescCTA = "Tu es juste à qu'elle que clic de Minefire"
